spring:
  application:
    name: GreenAtom
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: 123
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
token:
  secret: feuytbcewceut8Efq6c78tacrcFrRQQxafsddfcxasfdacffac
server:
  servlet:
    context-path: /api
